update:
  interval:
    years: 0
    months: 0
    weeks: 0
    days: 0
    hours: 
    minutes: 5
    seconds: 0
ranks:
  citizen:
    group: "citizen"
    message: "Welcome %p to citizenship"
    requirements:
      playtime:
        years: 0
        months: 0
        weeks: 0
        days: 0
        hours: 2
        minutes: 0
        seconds: 0
      votes:
        total: 5
  veteran:
    group: "veteran"
    message: "Welcome %p to the Veteran's Club"
    requirements:
      playtime:
        years: 0
        months: 1
        weeks: 0
        days: 0
        hours: 0
        minutes: 0
        seconds: 0
      votes:
        total: 100