main: com.retrontology.citizenship.Citizenship
name: Citizenship
version: 1.0.2
author: Retrontology
description: A plugin that automates citizenship and ranks through LuckPerms and VotingPlugin
depend: [VotingPlugin, LuckPerms]
permissions: 
  citizenship.admin:
    description: Required for using commands
    default: false
commands:
  visitor:
    description: Set player's primary group to default
    usage: /visitor <player>
  citizen:
    description: Set player's primary group to citizen
    usage: /citizen <player>
  veteran:
    description: Set player's primary group to veteran
    usage: /veteran <player>